sudo: required
language: node_js
python:
  - "2.7"
node_js:
  - "lts/*"
services:
  - docker

env:
  - NODE_ENV=production
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8

before_install:
- docker -v
- npm i --registry=www.kstudio.top:7001
script:
- docker build ./ --tag kinfen/kadm:app_last


after_success:
- docker login -u $YUN_USERNAME -p $YUN_PASSWORD
- docker push registry.cn-shenzhen.aliyuncs.com/kstudio/kadm:app_last


notifications:
  webhooks:
    urls:
      - http://www.kstudio.top:8082
    on_success: always # default: always
    on_failure: always # default: always
    on_start: never   # default: never
    on_cancel: always # default: always
    on_error: always # default: always